name: terraform

on: [push]

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/terraform-github-actions/fmt@v0.4.6

  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/terraform-github-actions/validate@v0.4.6
